#!/bin/sh

# if the branch is master, then fail.

branch="$(git symbolic-ref HEAD 2>/dev/null)" || \
       "$(git describe --contains --all HEAD)"

if [ "${remote_ref##refs/heads/}" = "master" ]; then
    printf "\e[31m%s\e[m\n" "[Error]"
    echo "Cannot push to master branch."
    exit 1
fi
