#!/bin/sh

# if the branch is master, then fail.

while read local_ref local_sha1 remote_ref remote_sha1
do
  if [[ "${remote_ref##refs/heads/}" = "master" ]]; then
    printf "\e[31m%s\e[m\n" "[Error]"
    echo "Cannot push to master branch."
    exit 1
  fi
done