#!/bin/sh

# if the branch is master, then fail.

branch="$(git symbolic-ref HEAD 2>/dev/null)" || \
       "$(git describe --contains --all HEAD)"

if [ "${branch##refs/heads/}" = "master" ]; then
    printf "\e[31m%s\n\e[m" "[Error]"
    echo "Cannot commit on master branch."
    exit 1
fi
